accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_id>/comments/create/', views.comment_create, name='comment_create'),
]

auth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    pass
    # article_set =   -> 특정한 유저가 볼 수 있도록 저장한 set을 볼 수 있도록 
    # comment_set 

articles/models.py
from django.db import models
from accounts.models import User # 방법1
from django.conf import settings # 방법2
from django.contrib.auth import get_user_model # 방법3
# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    # comment_set = 장고가 자동으로 추가해주는 칼럼 -> article이 comment에 접근
    
    # # 유저모델을 참조하는 경우
    # # 방법 1. (권장하지 않음)
    # user = models.ForeignKey(User, on_delete=models.CASCADE) # 변경가능성이 있는 데이터는 변수화해서 사용하는 것이 좋음
    
    # # 방법 2. (권장) settings.AUTH_USER_MODEL == 'accounts.User'
    # user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # settings에 있는 accounts.User를 가져와서 사용

    # 방법 3. (권장)
    # user: 게시물을 참조하는 사람
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE) # 첫번째 User를 가져옴 
    # user_id = 

class Comment(models.Model):
    content = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE) # 1 : N 관계 설정 / 내용과 article 객체가 들어감
    # article_id = 장고가 자동으로 추가해주는 칼럼

    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    # user_id =       -> user와 comment 1 : N 연결

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import User

class CustomUserCreationForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ('username', )

class CustomAuthenticationForm(AuthenticationForm):
    pass

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    # title = forms.CharField(
    #     label='제목입니다.',
    #     widget=forms.TextInput(
    #         attrs={'class': 'form-control'}
    #     )
    # )

    class Meta:
        model = Article
        # fields = '__all__'
        # fields = ('title', 'content',)
        exclude = ('user', )
        # 코드를 커스터마이징 하고 싶을 때 사용
        # widgets = {
        #     'title': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control'}),
        # }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        # fields = '__all__'
        fields = ('content', )

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.contrib.auth import login as auth_login  # 이름 중복으로 오류 발생할 수 있으므로
from django.contrib.auth import logout as auth_logout
# Create your views here.

def signup(request):
    # 로그인했는지
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST) # request.POST: 사용자가 입력한 데이터
        if form.is_valid():             # 데이터를 검증 후에 저장해야 함
            user = form.save()          # user 객체 하나를 저장
            auth_login(request, user)
            return redirect('articles:index')

    else:
        # user가 id와 password를 입력받는 빈 폼 
        form = CustomUserCreationForm()
        

    context = {
        'form': form,
    }

    return render(request, 'account_form.html', context)


def login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST) # 기존 정보를 request에 덮어씀

        if form.is_valid():
            # form인증이 되었다면, 
            # form의 get_user를 넣어주는 함수를 불러온다.
            auth_login(request, form.get_user()) # get_user: authentication에만 있는 기능 / 아이디를 찾아서 form에 불러오는 것
            # get_user 해당하는 아이디를 찾아서
            # form에 불러와 
            # 요청값에 씌움
            # login으로 하겠다. 
            # http://127.0.0.1:8000/accounts/login/?next=/articles/create/

            # 로그인 후 리디렉션 처리를 담당
            next_url = request.GET.get('next')  # => /articles/create/
            # 로그인 후 사용자를 리디렉션해야 하는 다음 페이지의 경로를 저장하는 데 사용

            return redirect(next_url or 'articles:index')
            # next 인자가 url에 있을 때 => '/articles/create/' or 'articles:index' -> '/articles/create/'
            # next 인자가 url에 없을 때 => None or 'articles:index' -> 'articles:index'


    else:
        form = CustomAuthenticationForm()

    context = {
        'form': form,
    }

    return render(request, 'account_form.html', context)


def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article     # index
from .forms import ArticleForm, CommentForm  # create
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):

    articles = Article.objects.all()  # 전체 게시물 조회
    form = CommentForm()

    context = {
        'articles':articles,          # context에 전체 게시물 담고
        'form': form,
    }

    return render(request, 'index.html', context)

@login_required
def create(request):
    # # 로그인을 안했다면
    # if not request.user.is_authenticated:
    #     return redirect('accounts:login') # 로그인 페이지로 돌아감


    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():                   # title, content는 request.POST에 들어있고 user는 들어있지 않아서 따로 넣어주어야 함
            article = form.save(commit=False) # 잠깐 멈춤
            article.user = request.user       # 로그인한 사람 정보를 입력후 / user 대신 user_id 이렇게 사용해도 됨
            article.save()                    # 저장
            return redirect('articles:index')

    else:
        form = ArticleForm()     # title, comment만 user X

    context = {
        'form': form,
    }

    return render(request, 'form.html', context)


@login_required
def comment_create(request, article_id):
    article = Article.objects.get(id=article_id)

    form = CommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user  # 어떤 사용자
        comment.article = article    # 어떤 게시물
        comment.save()

        return redirect('articles:index')

accounts/templates/account_form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}

{% if request.resolver_match.url_name == 'signup' %}
  <h1>회원가입</h1>
{% else %}
  <h1>로그인</h1>
{% endif %}


<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" class="btn btn-primary">
  
</form>

{% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}

<!-- 보내는 경로 -->
<form action="" method="POST"> 
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit">

</form>

{% endblock %}

articles/templates/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}


{% block body %}

<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit">
</form>


{% endblock %}

articles/templates/index.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}

<!-- 게시글의 개수만큼 출력 -->
{% for article in articles %}     
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{article.title}}</h5>
    <p class="card-text">{{article.content}}</p>
    <p class="card-text">{{article.user}}</p>
  </div>
  <!-- 로그인 했는지 -->
  {% if request.user.is_authenticated %}
  <div class="card-footer">
    <form action="{% url 'articles:comment_create' article_id=article.id %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit">
    </form>
  </div>
  {% endif %}
  
  <div class="card-footer">
    {% for comment in article.comment_set.all %}
      <p>{{comment.user}} : {{comment.content}}</p>
    {% endfor %}
  </div>
</div>
{% endfor %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>

  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'articles:index' %}">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <!-- 로그인을 한 상태 -->
          {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'accounts:logout' %}">logout</a>
            <a class="nav-link" href="{% url 'articles:create' %}">Create</a>
            <a class="nav-link disabled">{{user}}</a>  
            <!-- {{user}} : 현재 로그인한 사람 정보 출력 -->

          {% else %}
            <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
            <a class="nav-link" href="{% url 'accounts:login' %}">login</a>

          {% endif %}
        </div>
      </div>
    </div>
  </nav>

  <div class="container">
    {% block body %}

    {% endblock %}
    
  </div>

 
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>